-- Source-X shared accounts schema for external login server
CREATE TABLE IF NOT EXISTS accounts (
    name VARCHAR(32) NOT NULL PRIMARY KEY,
    password VARCHAR(128) NOT NULL DEFAULT '',
    blocked TINYINT(1) NOT NULL DEFAULT 0,
    priv INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
