-- Source-X shared accounts schema (SQLite, local testing)
CREATE TABLE IF NOT EXISTS accounts (
    name TEXT NOT NULL PRIMARY KEY COLLATE NOCASE,
    password TEXT NOT NULL DEFAULT '',
    blocked INTEGER NOT NULL DEFAULT 0,
    priv INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
