image: Visual Studio 2022
configuration: Nightly
platform: x64

install:
  - cmd: echo Setting up build environment

build_script:
  - cmd: cmake -G "Visual Studio 17 2022" -A x64 .
  - cmd: msbuild SphereServer.sln /p:Configuration=Nightly /verbosity:minimal /maxcpucount

test_script:
  - cmd: ctest --output-on-failure -C Nightly
