name: coverity-scan

on:
  push:
    branches: ["static-analysis", "master", "main"]
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.txt'
      - '**.md'
      - '**.rc'
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install prerequisites
      if: ${{ env.COVERITY_TOKEN != '' }}
      env:
        COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      run: |
        sudo add-apt-repository universe && sudo apt-get -qq update
        sudo apt-get install -yq --no-install-recommends \
          ninja-build gcc-12 g++-12 \
          mariadb-client libmariadb-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 90 --slave /usr/bin/g++ g++ /usr/bin/g++-12

    - name: Download Coverity Build Tool
      if: ${{ env.COVERITY_TOKEN != '' }}
      env:
        COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      run: |
        wget -nv https://scan.coverity.com/download/cxx/linux64 --post-data "token=${COVERITY_TOKEN}&project=Sphereserver/Source-X" -O cov-analysis-linux64.tar.gz
        mkdir cov-analysis-linux64
        tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64

    - name: CMake & Compilation (cov-build)
      if: ${{ env.COVERITY_TOKEN != '' }}
      run: |
        mkdir -p build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Nightly" -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/Linux-GNU-x86_64.cmake -S ./ -B ./build
        cd build
        ../cov-analysis-linux64/bin/cov-build --dir ./cov-int make -j$(nproc)

    - name: Submit the result to Coverity Scan
      if: ${{ env.COVERITY_TOKEN != '' }}
      env:
        COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
        COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
      run: |
        cd build
        tar czvf build-data.tgz cov-int
        curl \
          --form token=$COVERITY_TOKEN \
          --form email=$COVERITY_EMAIL \
          --form file=@build-data.tgz \
          --form version="trunk" \
          --form description="${{github.sha}}" \
          https://scan.coverity.com/builds?project=Sphereserver%2FSource-X
